# docker-compose.yml
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=gestiontic_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Uni2024+/
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=gestiontic.settings
    ports:
      - "8000:8000"
    depends_on:
      - db